- name: Установить MySQL сервер
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Установить PyMySQL (для работы mysql_* модулей)
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Убедиться, что лог-директория существует
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: Установить bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'

- name: Установить server-id
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^server-id' 
    line: "server-id = {{ mysql_server_id | int }}" # использовал каст к инту тк у меня была неприятная ситуация когда в конфиг попало значение FALSE вместо айдишника

- name: Включить бинарные логи
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^#?log_bin'
    line: 'log_bin = /var/log/mysql/mysql-bin.log'

- name: Перезапустить MySQL
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Создать базу данных wordpress
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: rootpass

- name: Создать пользователя WordPress
  mysql_user:
    name: wp_user
    password: wp_pass
    priv: "wordpress.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: rootpass

- name: Создать пользователя для репликации
  mysql_user:
    name: replica
    password: password
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    state: present
    login_user: root
    login_password: rootpass